# Generated by Django 5.1.4 on 2024-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite')], default='standard', max_length=200)),
                ('pricePerNight', models.IntegerField(default=150)),
                ('currencyType', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=200)),
                ('maxOccupancy', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='room_images/')),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
