# Generated by Django 5.1.4 on 2024-12-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_roomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BACKEND.room'),
        ),
    ]
