# Generated by Django 5.1.4 on 2024-12-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0004_rename_image_roomimage_images_alter_roomimage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='images',
            new_name='image',
        ),
    ]
